import React from "react";
import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import { Noto_Sans_Thai } from "next/font/google";
import Navbar from "@/components/navbar/navbar";

import "./globals.css";

const notoSansThai = Noto_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-notoSansThai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={notoSansThai.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
